
# SEO settings
title: 侯松的博客
description: "侯松的个人博客，发布大数据技术相关的各种原创文章"
keywords: "bigdata, hadoop, hbase, hive, presto, flume, spark"
url: http://housong.github.io
baseurl: ""
# baseurl: null

google_analytics: UA-71996864-1
disqus_shortname: "housong"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

paginate: 10
paginate_path: "/page/:num/"
comments: true

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Hou Song
  job      : Bigdata Engineer
  bio      : "我是一名专业的大数据工程师，写这个博客为了记录工作上和生活上的点滴收获。除了明确标明，均属于个人原创，任何形式的转载请联系本人。"
  thumb    : /images/author.jpeg
  email    : song.hou@gmail.com
  url      : http://housong.github.io
  github   : http://github.com/housong
  linkedin : https://linkedin.com/in/songhou

# social settings
og_locale: "zh_CN"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
